### ISSUE TITLE
 (0 , _stampUtils.compose) is not a function

### ISSUE THREAD

**Issue by Juli0GT** [learn-javascript-courses/composition-examples#2]
I've cloned your repo and installed node-modules. WHen I run npm test I get the following error.
`TypeError: (0 , _stampUtils.compose) is not a function
    at Object.<anonymous> (/Users/juliogt/Projects/Training/JS_Training/JS_EricElliot/composition-examples/examples/stamp-compose/index.js:19:22)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at normalLoader (/Users/juliogt/Projects/Training/JS_Training/JS_EricElliot/composition-examples/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/juliogt/Projects/Training/JS_Training/JS_EricElliot/composition-examples/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/juliogt/Projects/Training/JS_Training/JS_EricElliot/composition-examples/test/stamp-compose/index.js:1:24)`

**Comment by ericelliott** [comment]
Interesting. Try again. I've updated package.json to use the exact version that it was created with, and it worked for me:

```
git clone git@github.com:learn-javascript-courses/composition-examples.git
cd composition-examples
npm install && npm run test
```

Produced the following output:

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fsevents@1.2.4 install /Users/eric/Dropbox/dev/composition-examples/node_modules/fsevents
> node install

[fsevents] Success: "/Users/eric/Dropbox/dev/composition-examples/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm notice created a lockfile as package-lock.json. You should commit this file.
added 512 packages from 294 contributors and audited 1911 packages in 18.966s
found 13 vulnerabilities (7 low, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> composition-examples@1.0.1 test /Users/eric/Dropbox/dev/composition-examples
> babel-node test/index.js

TAP version 13
# shape()
# ...with prototype
ok 1 should reflect changes to the prototype
# ...with prototype
ok 2 local changes should not alter prototype
# highPass.filter()
# ...with n > 5
ok 3 should return true for values above cutoff
# ...with n < 5
ok 4 should return false for values below cutoff
# GuitarAmp
ok 5 should have volume, distortion, cabinet, and .apply()
# BassAmp
ok 6 should have volume, lowCut, cabinet, and .apply()
# GuitarAmp
ok 7 should have distortion, volume, cabinet and apply()
# BassAmp
ok 8 should have volume, lowCut, cabinet and apply()
# ChannelStrip
ok 9 should have inputLevel, lowCut, volume, and apply()
# filter.highPass()
# ...with n > cutoff
ok 10 should return true for values above cutoff
# ...with n < cutoff
ok 11 should return false for values below cutoff
# filter.lowPass()
# ...with n > cutoff
ok 12 should return false for values above cutoff
# ...with n < cutoff
ok 13 should return true for values below cutoff
# simple factory encapsulation filter.highPass()
# ...with n < highPassCutoff
ok 14 should return false for values below highPassCutoff
# ...with n > highPassCutoff
ok 15 should return true for values above highPassCutoff
# simple factory encapsulation filter.lowPass()
# ...with n < lowPassCutoff
ok 16 should return true for values below lowPassCutoff
# ...with n > lowPassCutoff
ok 17 should return false for values above lowPassCutoff
# simple compose filter.highPass()
# ...with n > cutoff
ok 18 should return true for values above cutoff
# ...with n < cutoff
ok 19 should return false for values below cutoff
# simple compose filter.lowPass()
# ...with n > cutoff
ok 20 should return false for values above cutoff
# ...with n < cutoff
ok 21 should return true for values below cutoff
# stamp compose filter.highPass()
# ...with n > cutoff
ok 22 should return true for values above cutoff
# ...with n < cutoff
ok 23 should return false for values below cutoff
# stamp compose filter.lowPass()
# ...with n > cutoff
ok 24 should return false for values above cutoff
# ...with n < cutoff
ok 25 should return true for values below cutoff

1..25
# tests 25
# pass  25

# ok
```

**Comment by ericelliott** [comment]
Closing because it seems to work. Reopen if you still need help.
